%This script converts a csv file generated by the PyAdaptation GUI into the
%datlog format formerly created by the AdaptationGUI in Matlab.
%WDA 8/31/2016
% clear
% clc

datlog = struct();
datlog.conversiontime = now;

[file,path] = uigetfile('*.*');

velL = importdata([path file],',',1);
velL = velL.data;
velR = importdata([path file],',',6);
velR = velR.data;
inca = importdata([path file],',',9);
inca = inca.data;
data = importdata([path file],',',13);
header = data.colheaders;
data = data.data;
reltime = 0;
for z = 2:length(data(:,1))
    reltime(z) = (data(z,1)-data(z-1,1))*0.01+reltime(z-1);
end

dateint = str2num(file(1:10));
temp = datestr(dateint/86400+datenum(1970,1,1));
a = regexp(temp,'-');
temp(a) = '_';
b = regexp(temp,':');
temp(b) = '_';
c = regexp(temp,' ');
temp(c) = '_';
savename = [path temp file(11:end-4) '.mat'];
datlog.session_name = savename;
datlog.errormsgs = {};
datlog.messages = {};
datlog.framenumbers.header = {'frame #','U Time','Relative Time'};
datlog.framenumbers.data = [data(:,1), nan(length(reltime),1), reltime'];
datlog.forces.header = {'frame #','U time','Rfz','Lfz','Relative Time'};
datlog.forces.data = [data(:,1),nan(length(reltime),1),data(:,2),data(:,3),reltime'];

datlog.stepdata.header = {'Event#','U time','frame #','Relative Time'};
temp = find(data(:,4));%RHS
datlog.stepdata.RHSdata = [[1:length(temp)]',nan(length(temp),1),data(temp,1),reltime(temp)'];
temp = find(data(:,5));%LHS
datlog.stepdata.LHSdata = [[1:length(temp)]',nan(length(temp),1),data(temp,1),reltime(temp)'];
temp = find(data(:,6));%RTO
datlog.stepdata.RTOdata = [[1:length(temp)]',nan(length(temp),1),data(temp,1),reltime(temp)'];
temp = find(data(:,7));%LTO
datlog.stepdata.LTOdata = [[1:length(temp)]',nan(length(temp),1),data(temp,1),reltime(temp)'];
clear temp;
datlog.inclineang = inca;

datlog.speedprofile.velL = velL;
datlog.speedprofile.velR = velR;

datlog.paused.header = {'frame #','Boolean'};
datlog.paused.data = [data(:,1),data(:,8)];

datlog.TreadmillCommands.header = {'RBS','LBS','angle','U Time','Relative Time'};
temp = find(~isnan(data(:,9)));
datlog.TreadmillCommands.sent = [data(temp,9),data(temp,10),inca*ones(length(temp),1),nan(length(temp),1),reltime(temp)'];
temp = find(~isnan(data(:,11)));
datlog.TreadmillCommands.read = [data(temp,11),data(temp,12),data(temp,13),nan(length(temp),1),reltime(temp)'];

save(savename,'datlog');














